
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use Neon's direct connection for build-time schema sync when available.
    // Keep DATABASE_URL as the runtime/compatibility fallback.
    url: process.env.DATABASE_URL_UNPOOLED || env("DATABASE_URL"),
  },
});
