
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Support the Vercel Prisma Postgres integration's default STORAGE_URL
    // prefix, and prefer direct URLs for build-time schema sync when present.
    url:
      process.env.STORAGE_URL ||
      process.env.DATABASE_URL_UNPOOLED ||
      env("DATABASE_URL"),
  },
});
